<template><div class="layout"><el-container style="height:100vh"><el-aside width="200px" class="sidebar"><div class="logo"><span>能耗监测</span></div><el-menu :default-active="route.path" router background-color="#001529" text-color="#ffffffb3" active-text-color="#1890ff"><el-menu-item index="/home"><el-icon><Odometer/></el-icon><span>首页</span></el-menu-item><el-sub-menu index="energy"><template #title><el-icon><DataLine/></el-icon><span>分项能耗</span></template><el-menu-item index="/energy-analysis">分项分析</el-menu-item><el-menu-item index="/energy-compare">分项对比</el-menu-item><el-menu-item index="/energy-ratio">分项比例</el-menu-item></el-sub-menu><el-sub-menu index="tenement"><template #title><el-icon><House/></el-icon><span>分户能耗</span></template><el-menu-item index="/tenement-analysis">分户分析</el-menu-item><el-menu-item index="/tenement-compare">分户对比</el-menu-item></el-sub-menu><el-sub-menu index="equipment"><template #title><el-icon><Setting/></el-icon><span>设备能耗</span></template><el-menu-item index="/equipment-analysis">设备分析</el-menu-item><el-menu-item index="/equipment-compare">设备对比</el-menu-item></el-sub-menu><el-sub-menu index="monitor"><template #title><el-icon><Cpu/></el-icon><span>监测数据</span></template><el-menu-item index="/realtime-data">实时数据</el-menu-item>
<el-menu-item index="/data-table">原始数据</el-menu-item>
<el-menu-item index="/data-alert">报警管理</el-menu-item></el-sub-menu><el-sub-menu index="report"><template #title><el-icon><Document/></el-icon><span>报表打印</span></template><el-menu-item index="/report-general">通用报表</el-menu-item><el-menu-item index="/report-branch">支路报表</el-menu-item><el-menu-item index="/report-custom">定制报表</el-menu-item></el-sub-menu></el-menu></el-aside><el-container><el-header class="header"><div>{{ app.buildingName || '能耗监测子系统' }} · {{ route.meta.title }}</div><div class="hr"><span>{{ auth.user?.username }}</span><el-button text size="small" @click="doLogout">退出</el-button></div></el-header><el-main class="main"><router-view/></el-main></el-container></el-container></div></template>
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'; import { useAuthStore, useAppStore } from '@/stores/index'
const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const app = useAppStore()
function doLogout() { auth.logout(); app.clearBuilding(); router.push('/login') }
</script>
<style scoped>.sidebar{background:#001529}.logo{display:flex;align-items:center;padding:16px 20px;color:#fff;font-size:15px;font-weight:600}.header{display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid #e8e8e8;padding:0 20px;height:48px;font-size:14px}.hr{display:flex;align-items:center;gap:12px;font-size:13px;color:#666}.main{background:#f5f5f5;padding:16px}</style>
