import r from './request'
export const login = (d: any) => r.post('/auth/login', d)
export const getMyBuilding = () => r.get('/auth/my_building')
export const getTitle = () => r.get('/auth/title')
export const getDashboardHomepage = (p: any) => r.get('/dashboard/homepage', { params: p })
export const getEnergyItems = (sign: string) => r.get('/energy/items', { params: { sign } })
export const getEnergyAnalysis = (p: any) => r.get('/energy/analysis', { params: p })
export const getEnergyRatio = (p: any) => r.get('/energy/ratio', { params: p })
export const getTenementList = (sign: string, energy_type: number = 1) => r.get('/tenement/list', { params: { sign, energy_type } })
export const getTenementAnalysis = (p: any) => r.get('/tenement/analysis', { params: p })
export const getEquipmentTree = (sign: string) => r.get('/equipment/tree', { params: { sign } })
export const getEquipmentAnalysis = (p: any) => r.get('/equipment/analysis', { params: p })
export const getServiceEnergy = (p: any) => r.get('/monitor/service/energy', { params: p })
export const getMeterList = (sign: string) => r.get('/monitor/meter/list', { params: { sign } })
export const getGeneralReport = (p: any) => r.get('/report/general', { params: p })
export const getBranchReport = (p: any) => r.get('/report/branch', { params: p })
export const getCustomReport = (p: any) => r.get('/report/custom', { params: p })
